services:
 
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - backend
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
        - action: sync
          path: ./frontend
          target: /usr/src/app
          ignore:
            - node_modules/
      

  backend:
    build: 
      context: ./backend
      target: development
    restart: always
    ports:
      - 8080:8080
    env_file: .env
    develop:
      watch:
        - action: rebuild 
          path: ./backend/pom.xml