spring.application.name=bank
spring.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DATABASE}
debug=false
management.endpoints.web.cors.allowed-origins=http://localhost:5173
logging.level.org.springframework.security=TRACE
